server:
  port: 8080

spring:
  application:
    name: restaurant-menu-admin-api

# GitHub Configuration
github:
  repository:
    url: https://github.com/ShubhamChouksey123/restaurant-menu.git
    branch: main
    username: ${GITHUB_USERNAME:ShubhamChouksey123}
    token: ${GITHUB_TOKEN:your-github-personal-access-token}

  menu:
    file-path: static/data/menu-data.json

  local:
    clone-directory: ${user.home}/.restaurant-menu-repo

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:your-super-secret-jwt-key-change-this-in-production}
  expiration: 86400000 # 24 hours in milliseconds

# Admin User Configuration (for initial setup)
admin:
  username: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD:admin123}
  email: ${ADMIN_EMAIL:admin@bapukikutia.com}

# CORS Configuration
cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Logging
logging:
  level:
    com.bapukikutia.menuadmin: DEBUG
    org.eclipse.jgit: INFO
    org.springframework.security: DEBUG
