name: Code Quality

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check file sizes
        run: |
          echo "Checking file sizes..."

          if [ -f "index.html" ]; then
            size=$(wc -c < index.html)
            kb=$((size / 1024))
            echo "index.html: ${kb}KB"
          fi

          if [ -f "static/css/styles.css" ]; then
            size=$(wc -c < static/css/styles.css)
            kb=$((size / 1024))
            echo "styles.css: ${kb}KB"
          fi

          if [ -f "static/js/script.js" ]; then
            size=$(wc -c < static/js/script.js)
            kb=$((size / 1024))
            echo "script.js: ${kb}KB"
          fi

      - name: Check HTML structure
        run: |
          echo "Checking HTML structure..."

          if [ -f "index.html" ]; then
            h1=$(grep -c "<h1" index.html || true)
            h2=$(grep -c "<h2" index.html || true)
            h3=$(grep -c "<h3" index.html || true)
            img=$(grep -c "<img" index.html || true)

            echo "H1: $h1, H2: $h2, H3: $h3"
            echo "Images: $img"
          fi

      - name: Complete
        run: echo "✅ Quality checks complete"
