name: Check Links

on:
  schedule:
    # Run weekly on Monday at 9:00 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:
  push:
    branches: [ master, main ]
    paths:
      - '**.html'
      - '**.md'

jobs:
  check-links:
    name: Check for Broken Links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check links in HTML files
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --accept 200,429 '**/*.html' '**/*.md'
          fail: true
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue on Broken Links
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🔗 Broken Links Detected',
              body: 'The link checker workflow has detected broken links. Please review the workflow logs for details.\n\n[View Workflow Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})',
              labels: ['bug', 'links']
            })
