name: Check Links

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  check-links:
    name: Check Internal Links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check links
        run: |
          echo "Checking internal links..."

          if grep -q "styles.css" index.html && [ -f "static/css/styles.css" ]; then
            echo "✅ CSS link valid"
          fi

          if grep -q "script.js" index.html && [ -f "static/js/script.js" ]; then
            echo "✅ JS link valid"
          fi

          if grep -q "gallery.html" index.html; then
            if [ -f "gallery.html" ]; then
              echo "✅ gallery.html exists"
            else
              echo "⚠️ gallery.html referenced but not created"
            fi
          fi

          if grep -q "contact.html" index.html; then
            if [ -f "contact.html" ]; then
              echo "✅ contact.html exists"
            else
              echo "⚠️ contact.html referenced but not created"
            fi
          fi

          echo "✅ Link check complete"
