name: Check Links

on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  check-links:
    name: Check Internal Links
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check internal links
        run: |
          echo "=== Checking Internal Links ==="

          # Check if gallery.html is referenced
          if grep -q "gallery.html" index.html; then
            if [ -f "gallery.html" ]; then
              echo "✅ gallery.html exists"
            else
              echo "⚠️ gallery.html referenced but not created yet"
            fi
          fi

          # Check if contact.html is referenced
          if grep -q "contact.html" index.html; then
            if [ -f "contact.html" ]; then
              echo "✅ contact.html exists"
            else
              echo "⚠️ contact.html referenced but not created yet"
            fi
          fi

          # Check CSS reference
          if grep -q "styles.css" index.html; then
            if [ -f "static/css/styles.css" ]; then
              echo "✅ CSS link valid"
            else
              echo "❌ CSS file missing"
              exit 1
            fi
          fi

          # Check JS reference
          if grep -q "script.js" index.html; then
            if [ -f "static/js/script.js" ]; then
              echo "✅ JS link valid"
            else
              echo "❌ JS file missing"
              exit 1
            fi
          fi

          echo "✅ Link check complete"
